apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vaultwarden
resources:
  - namespace.yaml
  - data-pvc.yaml
  - env-secret.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
