apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mediawiki-secret
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: mediawiki-secret
  dataFrom:
  - extract:
      key: mediawiki/mediawiki-secret
