apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: helm-values
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: helm-values
  dataFrom:
  - extract:
      key: authentik/helm-values
