apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: helm-values
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
    namespace: 
  target:
    name: helm-values
  data:
  - secretKey: foobar
    remoteRef:
      key: foo
      property: my-value