apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
spec:
  interval: 30m
  chart:
    spec:
      chart: authentik
      version: '2024.8.*'
      sourceRef:
        kind: HelmRepository
        name: authentik
      interval: 12h
  valuesFrom:
    - kind: Secret
      name: helm-values
      valuesKey: values.yaml
  timeout: 10m