apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: https://sro.soton.ac.uk:8200
      path: k8s-eso
      version: v2
      auth:
        tokenSecretRef:
          name: vault-token
          key: token
