apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: livecomp
resources:
  - namespace.yaml
  - postgres-pvc.yaml
  - postgres-env-secret.yaml
  - postgres-statefulset.yaml
  - postgres-service.yaml
