apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: server-env-secret
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: server-env
  dataFrom:
  - extract:
      key: livecomp/server/env
