apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
spec:
  interval: 30m
  chart:
    spec:
      chart: ingress-nginx
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
      interval: 12h
  values:
    controller:
      kind: DaemonSet
      service:
        type: NodePort
      publishService:
        enabled: false
      hostNetwork: true
      hostPort:
        enabled: true
      ingressClassResource:
        default: true
      watchIngressWithoutClass: true
      config:
        whitelist-source-range: '152.78.0.0/16,10.0.0.0/8,192.168.0.0/16,127.0.0.0/8,172.16.0.0/12'
    admissionWebhooks:
      enabled: false
