apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wiki
spec:
  interval: 30m
  chart:
    spec:
      chart: wiki
      version: '2.2.*'
      sourceRef:
        kind: HelmRepository
        name: wikijs
      interval: 12h
  values:
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      hosts:
      - host: wiki.roboticsoutreach.org
        paths:
        - path: /
          pathType: Prefix
      tls:
      - hosts:
        - wiki.roboticsoutreach.org
        secretName: wiki.roboticsoutreach.org-tls
