apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: livecomp-server
  namespace: flux-system
spec:
  image: ghcr.io/roboticsoutreach/livecomp-server
  interval: 1m
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: livecomp-server
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: livecomp-server
  filterTags:
    pattern: '^latest-(?P<ts>.*)'
    extract: '$ts'
  policy:
    numerical:
      order: asc
