apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ghost
spec:
  interval: 30m
  releaseName: ghost
  chartRef:
    kind: OCIRepository
    name: ghost
  values:
    ingress:
      enabled: true
      hostname: www.dev.roboticsoutreach.org
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      tls: true
    ghostBlogTitle: Southampton Robotics Outreach
    ghostEnableHttps: true
    resources:
      requests:
        cpu: 300m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 1Gi
    ghostSkipInstall: true # we can install it ourselves
  valuesFrom:
  - kind: Secret
    name: values
    valuesKey: ghostUsername
    targetPath: ghostUsername
  - kind: Secret
    name: values
    valuesKey: ghostPassword
    targetPath: ghostPassword
  - kind: Secret
    name: values
    valuesKey: mysql.auth.password
    targetPath: mysql.auth.password
  - kind: Secret
    name: values
    valuesKey: mysql.auth.rootPassword
    targetPath: mysql.auth.rootPassword
