apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ghost
spec:
  interval: 30m
  chart:
    spec:
      chart: ghost
      version: '22.1.*'
      sourceRef:
        kind: HelmRepository
        name: ghost
      interval: 12h
  values:
    ingress:
      enabled: true
      hostname: www.dev.roboticsoutreach.org
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      tls: true
    ghostBlogTitle: Southampton Robotics Outreach
  valuesFrom:
  - kind: Secret
    name: values
    valuesKey: ghostUsername
    targetPath: ghostUsername
  - kind: Secret
    name: values
    valuesKey: ghostPassword
    targetPath: ghostPassword
  - kind: Secret
    name: values
    valuesKey: mysql.auth.password
    targetPath: mysql.auth.password
  - kind: Secret
    name: values
    valuesKey: mysql.auth.rootPassword
    targetPath: mysql.auth.rootPassword
