apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mysql-env-secret
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: mysql-env
  dataFrom:
  - extract:
      key: ghost-www/mysql
