apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  serviceName: mysql
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 65534
          image: docker.io/bitnami/mysql:8.4
          imagePullPolicy: Always
          envFrom:
          - secretRef:
              name: mysql-env
          resources:
            requests:
              cpu: 300m
              memory: 500Mi
            limits:
              cpu: 900m
              memory: 1Gi
          ports:
          - containerPort: 3306
            protocol: TCP
            name: mysql
          volumeMounts:
          - name: data
            mountPath: /var/lib/mysql
            subPath: mysql-empty-subdir
            readOnly: false
          - name: socket
            mountPath: /var/run/mysqld
            readOnly: false
          - name: tmp
            mountPath: /tmp
            readOnly: false
    volumes:
      - name: data
        persistentVolumeClaim:
          claimName: mysql-pvc
      - name: tmp
        emptyDir:
          sizeLimit: 128Mi
      - name: socket
        emptyDir:
          sizeLimit: 128Mi
