apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: values-secret
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: values
  dataFrom:
  - extract:
      key: ghost-www/values
