apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: discord-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discord-bot
  serviceName: discord-bot
  template:
    metadata:
      labels:
        app: discord-bot
    spec:
      containers:
      - name: app
        image: ghcr.io/roboticsoutreach/discord-bot:latest-1739132613 # {"$imagepolicy": "flux-system:discord-bot"}
        resources:
          requests:
            memory: 128Mi
            cpu: 100m
          limits:
            memory: 512Mi
            cpu: 200m
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 1000
        volumeMounts:
        - name: data
          mountPath: /app
        envFrom:
        - secretRef:
            name: env
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: data-pvc
