apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault
spec:
  interval: 30m
  chart:
    spec:
      chart: vault
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: hashicorp
      interval: 12h
